// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpJccz90V0C_XAykescTvkgaXUEHAaM30',
    appId: '1:738367385448:web:6fc206fe2266d4ae5530dd',
    messagingSenderId: '738367385448',
    projectId: 'chatapp-cb92d',
    authDomain: 'chatapp-cb92d.firebaseapp.com',
    storageBucket: 'chatapp-cb92d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn4NTlRC6MsdK-ai_M0W9wHEyDuPKCSEw',
    appId: '1:738367385448:android:76418ffe6b17642b5530dd',
    messagingSenderId: '738367385448',
    projectId: 'chatapp-cb92d',
    storageBucket: 'chatapp-cb92d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu0z1dWLQo-7ahbyDGSyJnRy4r2ta-pn8',
    appId: '1:738367385448:ios:0c07c193662d7f465530dd',
    messagingSenderId: '738367385448',
    projectId: 'chatapp-cb92d',
    storageBucket: 'chatapp-cb92d.appspot.com',
    iosBundleId: 'com.example.chatSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu0z1dWLQo-7ahbyDGSyJnRy4r2ta-pn8',
    appId: '1:738367385448:ios:0c07c193662d7f465530dd',
    messagingSenderId: '738367385448',
    projectId: 'chatapp-cb92d',
    storageBucket: 'chatapp-cb92d.appspot.com',
    iosBundleId: 'com.example.chatSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpJccz90V0C_XAykescTvkgaXUEHAaM30',
    appId: '1:738367385448:web:3e6a33b3330d82855530dd',
    messagingSenderId: '738367385448',
    projectId: 'chatapp-cb92d',
    authDomain: 'chatapp-cb92d.firebaseapp.com',
    storageBucket: 'chatapp-cb92d.appspot.com',
  );
}
